# Generated by Django 4.2.5 on 2024-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('status', models.CharField(choices=[('good', 'Хорошая'), ('needs_review', 'Требует проверки'), ('bad', 'Плохая')], default='good', max_length=15)),
                ('source_link', models.URLField()),
            ],
        ),
    ]
